spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  zipkin:
    #el contexto es el container_name del servicio definido en el docker-compose
    base-url: http://zipkin:9411